### ISSUE TITLE
Update micro-USB footprint

### ISSUE THREAD

**Issue by awickert** [NorthernWidget/ALog-BottleLogger#13]
* Holes for strain relief (suggested by @pmarchetto); this will also help component stay in place, and will remain compatible with USB ports that lack feet to go in the holes
* Suggest lengthening solder pads to make it easier to fix jumpers during manufacturing

**Comment by awickert** [comment]
I'd suggest basing the design off of the following Sparkfun footprint, provided you can find the right part:
USB-B-MICRO-SMD_V03

![image](https://cloud.githubusercontent.com/assets/1714966/25971913/3d632018-369e-11e7-963c-552866289b30.png)

**Comment by superchap123** [comment]
Lengthened pads a while back, done.
