### ISSUE TITLE
change out level shifter and replace 3.3V regulators

### ISSUE THREAD

**Issue by superchap123** [NorthernWidget/ALog-BottleLogger#3]
Current level shifter has unused pins, could switch to this:  MC74HC125ADGOS-ND 

Could replace two 3.3V regulators with one part: 576-3453-1-ND

**Comment by awickert** [comment]
Kept current level shifter -- common, inexpensive component (CMOS 4050)

Replaced 3V3 with this amazingly tiny and nice regulator!
